 function [feature]=FuncSkin(image, opt)
option = struct(...
    'win_size', [],...
    'sbin', 8,...
    'ProcessFunc', @FuncSkin, ...
    'unique_tag', 'skin',...
    'tag', ''...
    );

 
mask=detect_skin(image, opt);
mask=mask>1;
feature=features_skin_ratio(mask,double(image), option.sbin);
feature = feature(:)';
end