 function [feature]=FuncLBP(image, opt)
 
option=struct(...
    'win_size', [], ...
    'sbin',25,...
    'unique_tag','lbp',...
    'tag', '',...
    'verbose',1 ...
);
if size(image,3)==3
    image=double(rgb2gray(uint8(image)));
else
    image=double(image);
end

feature=features_lbp_new(image, option.sbin);
feature=feature(:)';
end