function feat = FuncCM(image, opt)

option=struct(...
    'win_size',[],...
    ...dense grid option
    'cell_size',[16,16],...
    'cell_stride',[8,8],...   
    'hist_dim', 3, ...
    'hist_bin',8,...
    'gamma', 2.5, ...
    'fea_size',0,...
    'unique_tag', 'ColorHist',...
    'tag', '', ...
    'verbose',1 ...
);
 
 
 
feature=[];
% pos =[];
j=10;
temp = features_cm(image,j);
fea_dim = size(temp,3);
feature=[feature,reshape(temp,size(temp,1)*size(temp,2),fea_dim)'];
feat =feature(:);